#include <test.h>

void TestJson::QMJsonValue_create(void)
{
    auto value00 = QMPointer<QMJsonValue>(new QMJsonValue());
    auto value01 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value02 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto value03 = QMPointer<QMJsonValue>(new QMJsonValue(QString("Hello World")));
    auto value04 = QMPointer<QMJsonValue>(new QMJsonValue(QMPointer<QMJsonValue>(new QMJsonValue())));
    auto value05 = QMPointer<QMJsonValue>(new QMJsonValue(QMPointer<QMJsonArray>(new QMJsonArray())));
    auto value06 = QMPointer<QMJsonValue>(new QMJsonValue(QMPointer<QMJsonObject>(new QMJsonObject())));
    auto value07 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonValue()));
    auto value08 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonArray()));
    auto value09 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonObject()));
    auto value10 = QMPointer<QMJsonValue>(new QMJsonValue(QRect()));
    auto value11 = QMPointer<QMJsonValue>(new QMJsonValue("Hello World"));
    auto value12 = QMPointer<QMJsonValue>(new QMJsonValue((short)4));
    auto value13 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned short)8));
    auto value14 = QMPointer<QMJsonValue>(new QMJsonValue((int)15));
    auto value15 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned int)16));
    auto value16 = QMPointer<QMJsonValue>(new QMJsonValue((long)23));
    auto value17 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned long)42));
    auto value18 = QMPointer<QMJsonValue>(new QMJsonValue((long long)4));
    auto value19 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned long long)8));
    auto value20 = QMPointer<QMJsonValue>(new QMJsonValue(QMPointer<QMJsonValue>()));
    auto value21 = QMPointer<QMJsonValue>(new QMJsonValue(QMPointer<QMJsonArray>()));
    auto value22 = QMPointer<QMJsonValue>(new QMJsonValue(QMPointer<QMJsonObject>()));

    QVERIFY(value00->type() == QMJsonValueType_Null);
    QVERIFY(value01->type() == QMJsonValueType_Bool);
    QVERIFY(value02->type() == QMJsonValueType_Double);
    QVERIFY(value03->type() == QMJsonValueType_String);
    QVERIFY(value04->type() == QMJsonValueType_Null);
    QVERIFY(value05->type() == QMJsonValueType_Array);
    QVERIFY(value06->type() == QMJsonValueType_Object);
    QVERIFY(value07->type() == QMJsonValueType_Null);
    QVERIFY(value08->type() == QMJsonValueType_Array);
    QVERIFY(value09->type() == QMJsonValueType_Object);
    QVERIFY(value10->type() == QMJsonValueType_Custom);
    QVERIFY(value11->type() == QMJsonValueType_String);
    QVERIFY(value12->type() == QMJsonValueType_Double);
    QVERIFY(value13->type() == QMJsonValueType_Double);
    QVERIFY(value14->type() == QMJsonValueType_Double);
    QVERIFY(value15->type() == QMJsonValueType_Double);
    QVERIFY(value16->type() == QMJsonValueType_Double);
    QVERIFY(value17->type() == QMJsonValueType_Double);
    QVERIFY(value18->type() == QMJsonValueType_Double);
    QVERIFY(value19->type() == QMJsonValueType_Double);
    QVERIFY(value20->type() == QMJsonValueType_Null);
    QVERIFY(value21->type() == QMJsonValueType_Array);
    QVERIFY(value22->type() == QMJsonValueType_Object);

    QVERIFY(value00->typeString() == "QMJsonValueType_Null");
    QVERIFY(value01->typeString() == "QMJsonValueType_Bool");
    QVERIFY(value02->typeString() == "QMJsonValueType_Double");
    QVERIFY(value03->typeString() == "QMJsonValueType_String");
    QVERIFY(value04->typeString() == "QMJsonValueType_Null");
    QVERIFY(value05->typeString() == "QMJsonValueType_Array");
    QVERIFY(value06->typeString() == "QMJsonValueType_Object");
    QVERIFY(value07->typeString() == "QMJsonValueType_Null");
    QVERIFY(value08->typeString() == "QMJsonValueType_Array");
    QVERIFY(value09->typeString() == "QMJsonValueType_Object");
    QVERIFY(value10->typeString() == "QMJsonValueType_Custom");
    QVERIFY(value11->typeString() == "QMJsonValueType_String");
    QVERIFY(value12->typeString() == "QMJsonValueType_Double");
    QVERIFY(value13->typeString() == "QMJsonValueType_Double");
    QVERIFY(value14->typeString() == "QMJsonValueType_Double");
    QVERIFY(value15->typeString() == "QMJsonValueType_Double");
    QVERIFY(value16->typeString() == "QMJsonValueType_Double");
    QVERIFY(value17->typeString() == "QMJsonValueType_Double");
    QVERIFY(value18->typeString() == "QMJsonValueType_Double");
    QVERIFY(value19->typeString() == "QMJsonValueType_Double");
    QVERIFY(value20->typeString() == "QMJsonValueType_Null");
    QVERIFY(value21->typeString() == "QMJsonValueType_Array");
    QVERIFY(value22->typeString() == "QMJsonValueType_Object");
}

void TestJson::QMJsonValue_file(void)
{
    auto object1 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto value1 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value2 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto value3 = QMPointer<QMJsonValue>(new QMJsonValue("Hello World"));
    auto document1 = QMPointer<QMJsonValue>(new QMJsonValue(object1));

    object1->insert("key1", value1);
    object1->insert("key2", value2);
    object1->insert("key3", value3);

    QVERIFY(document1->toJsonFile("test.json") == true);

    auto document2 = QMJsonValue::fromJsonFile("test.json");

    QVERIFY(document2.isNull() == false);
    QVERIFY(document1->toJson(QMJsonFormat_Optimized, QMJsonSort_CaseSensitive) ==
            document2->toJson(QMJsonFormat_Optimized, QMJsonSort_CaseSensitive));
}

void TestJson::QMJsonValue_sort(void)
{
    auto object1 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto object2 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto object3 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto object4 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto object5 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto object6 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto value1 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value2 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto value3 = QMPointer<QMJsonValue>(new QMJsonValue("Hello World"));
    auto document1 = QMPointer<QMJsonValue>(new QMJsonValue(object5));
    auto document2 = QMPointer<QMJsonValue>(new QMJsonValue(object6));

    object1->insert("apple", value1);
    object1->insert("Baseball", value2);
    object1->insert("cat", value3);

    object2->insert("Baseball", value2);
    object2->insert("apple", value1);
    object2->insert("cat", value3);

    object3->insert("cat", value3);
    object3->insert("apple", value1);
    object3->insert("Baseball", value2);

    object4->insert("cat", value3);
    object4->insert("Baseball", value2);
    object4->insert("apple", value1);

    object5->insert("dog", object1);
    object5->insert("evil", object2);

    object6->insert("evil", object4);
    object6->insert("dog", object3);

    QVERIFY(document1->toJson(QMJsonFormat_Optimized, QMJsonSort_CaseSensitive) !=
            document2->toJson(QMJsonFormat_Optimized, QMJsonSort_CaseInsensitive));

    QVERIFY(document1->toJson(QMJsonFormat_Optimized, QMJsonSort_CaseInsensitive) ==
            document2->toJson(QMJsonFormat_Optimized, QMJsonSort_CaseInsensitive));

    QVERIFY(document1->toJson(QMJsonFormat_Optimized, QMJsonSort_CaseSensitive) ==
            document2->toJson(QMJsonFormat_Optimized, QMJsonSort_CaseSensitive));
}

void TestJson::QMJsonValue_bool(void)
{
    auto value00 = QMPointer<QMJsonValue>(new QMJsonValue());
    auto value01 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value02 = QMPointer<QMJsonValue>(new QMJsonValue(false));
    auto value03 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto value04 = QMPointer<QMJsonValue>(new QMJsonValue(0));
    auto value05 = QMPointer<QMJsonValue>(new QMJsonValue("true"));
    auto value06 = QMPointer<QMJsonValue>(new QMJsonValue("false"));
    auto value07 = QMPointer<QMJsonValue>(new QMJsonValue("Hello World"));
    auto value08 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonArray));
    auto value09 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonObject));
    auto value10 = QMPointer<QMJsonValue>(new QMJsonValue(QRect()));

    QVERIFY(value00->isBool() == false);
    QVERIFY(value01->isBool() == true);
    QVERIFY(value02->isBool() == true);
    QVERIFY(value03->isBool() == false);
    QVERIFY(value04->isBool() == false);
    QVERIFY(value05->isBool() == false);
    QVERIFY(value06->isBool() == false);
    QVERIFY(value07->isBool() == false);
    QVERIFY(value08->isBool() == false);
    QVERIFY(value09->isBool() == false);
    QVERIFY(value10->isBool() == false);

    QVERIFY(value00->toBool() == false);
    QVERIFY(value01->toBool() == true);
    QVERIFY(value02->toBool() == false);
    QVERIFY(value03->toBool() == true);
    QVERIFY(value04->toBool() == false);
    QVERIFY(value05->toBool() == true);
    QVERIFY(value06->toBool() == false);
    QVERIFY(value07->toBool() == false);
    QVERIFY(value08->toBool() == false);
    QVERIFY(value09->toBool() == false);
    QVERIFY(value10->toBool() == false);

    QVERIFY(value00->toBool(true) == true);
    QVERIFY(value01->toBool(true) == true);
    QVERIFY(value02->toBool(true) == false);
    QVERIFY(value03->toBool(true) == true);
    QVERIFY(value04->toBool(true) == true);
    QVERIFY(value05->toBool(true) == true);
    QVERIFY(value06->toBool(true) == true);
    QVERIFY(value07->toBool(true) == true);
    QVERIFY(value08->toBool(true) == true);
    QVERIFY(value09->toBool(true) == true);
    QVERIFY(value10->toBool(true) == true);

    QVERIFY(value00->to<bool>(true) == true);
    QVERIFY(value01->to<bool>(true) == true);
    QVERIFY(value02->to<bool>(true) == false);
    QVERIFY(value03->to<bool>(true) == true);
    QVERIFY(value04->to<bool>(true) == true);
    QVERIFY(value05->to<bool>(true) == true);
    QVERIFY(value06->to<bool>(true) == true);
    QVERIFY(value07->to<bool>(true) == true);
    QVERIFY(value08->to<bool>(true) == true);
    QVERIFY(value09->to<bool>(true) == true);
    QVERIFY(value10->to<bool>(true) == true);
}

void TestJson::QMJsonValue_double(void)
{
    auto value00 = QMPointer<QMJsonValue>(new QMJsonValue());
    auto value01 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value02 = QMPointer<QMJsonValue>(new QMJsonValue(false));
    auto value03 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto value04 = QMPointer<QMJsonValue>(new QMJsonValue("4.8"));
    auto value05 = QMPointer<QMJsonValue>(new QMJsonValue("Hello World"));
    auto value06 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonArray));
    auto value07 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonObject));
    auto value08 = QMPointer<QMJsonValue>(new QMJsonValue(QRect()));
    auto value09 = QMPointer<QMJsonValue>(new QMJsonValue((float)4.8));
    auto value10 = QMPointer<QMJsonValue>(new QMJsonValue((char)15));
    auto value11 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned char)16));
    auto value12 = QMPointer<QMJsonValue>(new QMJsonValue((short)23));
    auto value13 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned short)42));
    auto value14 = QMPointer<QMJsonValue>(new QMJsonValue((int)4));
    auto value15 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned int)8));
    auto value16 = QMPointer<QMJsonValue>(new QMJsonValue((long)15));
    auto value17 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned long)16));
    auto value18 = QMPointer<QMJsonValue>(new QMJsonValue((long long)23));
    auto value19 = QMPointer<QMJsonValue>(new QMJsonValue((unsigned long long)42));

    QVERIFY(value00->isDouble() == false);
    QVERIFY(value01->isDouble() == false);
    QVERIFY(value02->isDouble() == false);
    QVERIFY(value03->isDouble() == true);
    QVERIFY(value04->isDouble() == false);
    QVERIFY(value05->isDouble() == false);
    QVERIFY(value06->isDouble() == false);
    QVERIFY(value07->isDouble() == false);
    QVERIFY(value08->isDouble() == false);
    QVERIFY(value09->isDouble() == true);
    QVERIFY(value10->isDouble() == true);
    QVERIFY(value11->isDouble() == true);
    QVERIFY(value12->isDouble() == true);
    QVERIFY(value13->isDouble() == true);
    QVERIFY(value14->isDouble() == true);
    QVERIFY(value15->isDouble() == true);
    QVERIFY(value16->isDouble() == true);
    QVERIFY(value17->isDouble() == true);
    QVERIFY(value18->isDouble() == true);
    QVERIFY(value19->isDouble() == true);

    QVERIFY(value00->toDouble() == 0);
    QVERIFY(value01->toDouble() == 1);
    QVERIFY(value02->toDouble() == 0);
    QVERIFY(value03->toDouble() == 4.8);
    QVERIFY(value04->toDouble() == 4.8);
    QVERIFY(value05->toDouble() == 0);
    QVERIFY(value06->toDouble() == 0);
    QVERIFY(value07->toDouble() == 0);
    QVERIFY(value08->toDouble() == 0);
    QVERIFY(value09->toDouble() == (float)4.8);
    QVERIFY(value10->toDouble() == 15);
    QVERIFY(value11->toDouble() == 16);
    QVERIFY(value12->toDouble() == 23);
    QVERIFY(value13->toDouble() == 42);
    QVERIFY(value14->toDouble() == 4);
    QVERIFY(value15->toDouble() == 8);
    QVERIFY(value16->toDouble() == 15);
    QVERIFY(value17->toDouble() == 16);
    QVERIFY(value18->toDouble() == 23);
    QVERIFY(value19->toDouble() == 42);

    QVERIFY(value00->toDouble(15.16) == 15.16);
    QVERIFY(value01->toDouble(15.16) == 15.16);
    QVERIFY(value02->toDouble(15.16) == 15.16);
    QVERIFY(value03->toDouble(15.16) == 4.8);
    QVERIFY(value04->toDouble(15.16) == 15.16);
    QVERIFY(value05->toDouble(15.16) == 15.16);
    QVERIFY(value06->toDouble(15.16) == 15.16);
    QVERIFY(value07->toDouble(15.16) == 15.16);
    QVERIFY(value08->toDouble(15.16) == 15.16);
    QVERIFY(value09->toDouble(15.16) == (float)4.8);
    QVERIFY(value10->toDouble(15.16) == 15);
    QVERIFY(value11->toDouble(15.16) == 16);
    QVERIFY(value12->toDouble(15.16) == 23);
    QVERIFY(value13->toDouble(15.16) == 42);
    QVERIFY(value14->toDouble(15.16) == 4);
    QVERIFY(value15->toDouble(15.16) == 8);
    QVERIFY(value16->toDouble(15.16) == 15);
    QVERIFY(value17->toDouble(15.16) == 16);
    QVERIFY(value18->toDouble(15.16) == 23);
    QVERIFY(value19->toDouble(15.16) == 42);

    QVERIFY(value00->to<double>(15.16) == 15.16);
    QVERIFY(value01->to<double>(15.16) == 15.16);
    QVERIFY(value02->to<double>(15.16) == 15.16);
    QVERIFY(value03->to<double>(15.16) == 4.8);
    QVERIFY(value04->to<double>(15.16) == 15.16);
    QVERIFY(value05->to<double>(15.16) == 15.16);
    QVERIFY(value06->to<double>(15.16) == 15.16);
    QVERIFY(value07->to<double>(15.16) == 15.16);
    QVERIFY(value08->to<double>(15.16) == 15.16);
    QVERIFY(value09->to<double>(15.16) == (float)4.8);
    QVERIFY(value10->to<double>(15.16) == 15);
    QVERIFY(value11->to<double>(15.16) == 16);
    QVERIFY(value12->to<double>(15.16) == 23);
    QVERIFY(value13->to<double>(15.16) == 42);
    QVERIFY(value14->to<double>(15.16) == 4);
    QVERIFY(value15->to<double>(15.16) == 8);
    QVERIFY(value16->to<double>(15.16) == 15);
    QVERIFY(value17->to<double>(15.16) == 16);
    QVERIFY(value18->to<double>(15.16) == 23);
    QVERIFY(value19->to<double>(15.16) == 42);

    QVERIFY(value00->toFloat() == 0);
    QVERIFY(value01->toFloat() == 1);
    QVERIFY(value02->toFloat() == 0);
    QVERIFY(value03->toFloat() == (float)4.8);
    QVERIFY(value04->toFloat() == (float)4.8);
    QVERIFY(value05->toFloat() == 0);
    QVERIFY(value06->toFloat() == 0);
    QVERIFY(value07->toFloat() == 0);
    QVERIFY(value08->toFloat() == 0);
    QVERIFY(value09->toFloat() == (float)4.8);
    QVERIFY(value10->toFloat() == 15);
    QVERIFY(value11->toFloat() == 16);
    QVERIFY(value12->toFloat() == 23);
    QVERIFY(value13->toFloat() == 42);
    QVERIFY(value14->toFloat() == 4);
    QVERIFY(value15->toFloat() == 8);
    QVERIFY(value16->toFloat() == 15);
    QVERIFY(value17->toFloat() == 16);
    QVERIFY(value18->toFloat() == 23);
    QVERIFY(value19->toFloat() == 42);

    QVERIFY(value00->toFloat(15.16) == (float)15.16);
    QVERIFY(value01->toFloat(15.16) == (float)15.16);
    QVERIFY(value02->toFloat(15.16) == (float)15.16);
    QVERIFY(value03->toFloat(15.16) == (float)4.8);
    QVERIFY(value04->toFloat(15.16) == (float)15.16);
    QVERIFY(value05->toFloat(15.16) == (float)15.16);
    QVERIFY(value06->toFloat(15.16) == (float)15.16);
    QVERIFY(value07->toFloat(15.16) == (float)15.16);
    QVERIFY(value08->toFloat(15.16) == (float)15.16);
    QVERIFY(value09->toFloat(15.16) == (float)4.8);
    QVERIFY(value10->toFloat(15.16) == 15);
    QVERIFY(value11->toFloat(15.16) == 16);
    QVERIFY(value12->toFloat(15.16) == 23);
    QVERIFY(value13->toFloat(15.16) == 42);
    QVERIFY(value14->toFloat(15.16) == 4);
    QVERIFY(value15->toFloat(15.16) == 8);
    QVERIFY(value16->toFloat(15.16) == 15);
    QVERIFY(value17->toFloat(15.16) == 16);
    QVERIFY(value18->toFloat(15.16) == 23);
    QVERIFY(value19->toFloat(15.16) == 42);

    QVERIFY(value00->to<float>(15.16) == (float)15.16);
    QVERIFY(value01->to<float>(15.16) == (float)15.16);
    QVERIFY(value02->to<float>(15.16) == (float)15.16);
    QVERIFY(value03->to<float>(15.16) == (float)15.16);
    QVERIFY(value04->to<float>(15.16) == (float)15.16);
    QVERIFY(value05->to<float>(15.16) == (float)15.16);
    QVERIFY(value06->to<float>(15.16) == (float)15.16);
    QVERIFY(value07->to<float>(15.16) == (float)15.16);
    QVERIFY(value08->to<float>(15.16) == (float)15.16);
    QVERIFY(value09->to<float>(15.16) == (float)15.16);
    QVERIFY(value10->to<float>(15.16) == (float)15.16);
    QVERIFY(value11->to<float>(15.16) == (float)15.16);
    QVERIFY(value12->to<float>(15.16) == (float)15.16);
    QVERIFY(value13->to<float>(15.16) == (float)15.16);
    QVERIFY(value14->to<float>(15.16) == (float)15.16);
    QVERIFY(value15->to<float>(15.16) == (float)15.16);
    QVERIFY(value16->to<float>(15.16) == (float)15.16);
    QVERIFY(value17->to<float>(15.16) == (float)15.16);
    QVERIFY(value18->to<float>(15.16) == (float)15.16);
    QVERIFY(value19->to<float>(15.16) == (float)15.16);

    QVERIFY(value00->toChar() == 0);
    QVERIFY(value01->toChar() == 1);
    QVERIFY(value02->toChar() == 0);
    QVERIFY(value03->toChar() == 4);
    QVERIFY(value04->toChar() == 4);
    QVERIFY(value05->toChar() == 0);
    QVERIFY(value06->toChar() == 0);
    QVERIFY(value07->toChar() == 0);
    QVERIFY(value08->toChar() == 0);
    QVERIFY(value09->toChar() == 4);
    QVERIFY(value10->toChar() == 15);
    QVERIFY(value11->toChar() == 16);
    QVERIFY(value12->toChar() == 23);
    QVERIFY(value13->toChar() == 42);
    QVERIFY(value14->toChar() == 4);
    QVERIFY(value15->toChar() == 8);
    QVERIFY(value16->toChar() == 15);
    QVERIFY(value17->toChar() == 16);
    QVERIFY(value18->toChar() == 23);
    QVERIFY(value19->toChar() == 42);

    QVERIFY(value00->toChar(4) ==  4);
    QVERIFY(value01->toChar(8) ==  8);
    QVERIFY(value02->toChar(15) == 15);
    QVERIFY(value03->toChar(16) ==  4);
    QVERIFY(value04->toChar(23) == 23);
    QVERIFY(value05->toChar(42) == 42);
    QVERIFY(value06->toChar(4) ==  4);
    QVERIFY(value07->toChar(8) ==  8);
    QVERIFY(value08->toChar(15) == 15);
    QVERIFY(value09->toChar(16) ==  4);
    QVERIFY(value10->toChar(23) == 15);
    QVERIFY(value11->toChar(42) == 16);
    QVERIFY(value12->toChar(4) == 23);
    QVERIFY(value13->toChar(8) == 42);
    QVERIFY(value14->toChar(15) ==  4);
    QVERIFY(value15->toChar(16) ==  8);
    QVERIFY(value16->toChar(23) == 15);
    QVERIFY(value17->toChar(42) == 16);
    QVERIFY(value18->toChar(4) == 23);
    QVERIFY(value19->toChar(8) == 42);

    QVERIFY(value00->to<char>(4) ==  4);
    QVERIFY(value01->to<char>(8) ==  8);
    QVERIFY(value02->to<char>(15) == 15);
    QVERIFY(value03->to<char>(16) == 16);
    QVERIFY(value04->to<char>(23) == 23);
    QVERIFY(value05->to<char>(42) == 42);
    QVERIFY(value06->to<char>(4) ==  4);
    QVERIFY(value07->to<char>(8) ==  8);
    QVERIFY(value08->to<char>(15) == 15);
    QVERIFY(value09->to<char>(16) == 16);
    QVERIFY(value10->to<char>(23) == 23);
    QVERIFY(value11->to<char>(42) == 42);
    QVERIFY(value12->to<char>(4) ==  4);
    QVERIFY(value13->to<char>(8) ==  8);
    QVERIFY(value14->to<char>(15) == 15);
    QVERIFY(value15->to<char>(16) == 16);
    QVERIFY(value16->to<char>(23) == 23);
    QVERIFY(value17->to<char>(42) == 42);
    QVERIFY(value18->to<char>(4) ==  4);
    QVERIFY(value19->to<char>(8) ==  8);

    QVERIFY(value00->toUChar() == 0);
    QVERIFY(value01->toUChar() == 1);
    QVERIFY(value02->toUChar() == 0);
    QVERIFY(value03->toUChar() == 4);
    QVERIFY(value04->toUChar() == 4);
    QVERIFY(value05->toUChar() == 0);
    QVERIFY(value06->toUChar() == 0);
    QVERIFY(value07->toUChar() == 0);
    QVERIFY(value08->toUChar() == 0);
    QVERIFY(value09->toUChar() == 4);
    QVERIFY(value10->toUChar() == 15);
    QVERIFY(value11->toUChar() == 16);
    QVERIFY(value12->toUChar() == 23);
    QVERIFY(value13->toUChar() == 42);
    QVERIFY(value14->toUChar() == 4);
    QVERIFY(value15->toUChar() == 8);
    QVERIFY(value16->toUChar() == 15);
    QVERIFY(value17->toUChar() == 16);
    QVERIFY(value18->toUChar() == 23);
    QVERIFY(value19->toUChar() == 42);

    QVERIFY(value00->toUChar(4) ==  4);
    QVERIFY(value01->toUChar(8) ==  8);
    QVERIFY(value02->toUChar(15) == 15);
    QVERIFY(value03->toUChar(16) ==  4);
    QVERIFY(value04->toUChar(23) == 23);
    QVERIFY(value05->toUChar(42) == 42);
    QVERIFY(value06->toUChar(4) ==  4);
    QVERIFY(value07->toUChar(8) ==  8);
    QVERIFY(value08->toUChar(15) == 15);
    QVERIFY(value09->toUChar(16) ==  4);
    QVERIFY(value10->toUChar(23) == 15);
    QVERIFY(value11->toUChar(42) == 16);
    QVERIFY(value12->toUChar(4) == 23);
    QVERIFY(value13->toUChar(8) == 42);
    QVERIFY(value14->toUChar(15) ==  4);
    QVERIFY(value15->toUChar(16) ==  8);
    QVERIFY(value16->toUChar(23) == 15);
    QVERIFY(value17->toUChar(42) == 16);
    QVERIFY(value18->toUChar(4) == 23);
    QVERIFY(value19->toUChar(8) == 42);

    QVERIFY(value00->to<unsigned char>(4) ==  4);
    QVERIFY(value01->to<unsigned char>(8) ==  8);
    QVERIFY(value02->to<unsigned char>(15) == 15);
    QVERIFY(value03->to<unsigned char>(16) == 16);
    QVERIFY(value04->to<unsigned char>(23) == 23);
    QVERIFY(value05->to<unsigned char>(42) == 42);
    QVERIFY(value06->to<unsigned char>(4) ==  4);
    QVERIFY(value07->to<unsigned char>(8) ==  8);
    QVERIFY(value08->to<unsigned char>(15) == 15);
    QVERIFY(value09->to<unsigned char>(16) == 16);
    QVERIFY(value10->to<unsigned char>(23) == 23);
    QVERIFY(value11->to<unsigned char>(42) == 42);
    QVERIFY(value12->to<unsigned char>(4) ==  4);
    QVERIFY(value13->to<unsigned char>(8) ==  8);
    QVERIFY(value14->to<unsigned char>(15) == 15);
    QVERIFY(value15->to<unsigned char>(16) == 16);
    QVERIFY(value16->to<unsigned char>(23) == 23);
    QVERIFY(value17->to<unsigned char>(42) == 42);
    QVERIFY(value18->to<unsigned char>(4) ==  4);
    QVERIFY(value19->to<unsigned char>(8) ==  8);

    QVERIFY(value00->toShort() == 0);
    QVERIFY(value01->toShort() == 1);
    QVERIFY(value02->toShort() == 0);
    QVERIFY(value03->toShort() == 4);
    QVERIFY(value04->toShort() == 4);
    QVERIFY(value05->toShort() == 0);
    QVERIFY(value06->toShort() == 0);
    QVERIFY(value07->toShort() == 0);
    QVERIFY(value08->toShort() == 0);
    QVERIFY(value09->toShort() == 4);
    QVERIFY(value10->toShort() == 15);
    QVERIFY(value11->toShort() == 16);
    QVERIFY(value12->toShort() == 23);
    QVERIFY(value13->toShort() == 42);
    QVERIFY(value14->toShort() == 4);
    QVERIFY(value15->toShort() == 8);
    QVERIFY(value16->toShort() == 15);
    QVERIFY(value17->toShort() == 16);
    QVERIFY(value18->toShort() == 23);
    QVERIFY(value19->toShort() == 42);

    QVERIFY(value00->toShort(4) ==  4);
    QVERIFY(value01->toShort(8) ==  8);
    QVERIFY(value02->toShort(15) == 15);
    QVERIFY(value03->toShort(16) ==  4);
    QVERIFY(value04->toShort(23) == 23);
    QVERIFY(value05->toShort(42) == 42);
    QVERIFY(value06->toShort(4) ==  4);
    QVERIFY(value07->toShort(8) ==  8);
    QVERIFY(value08->toShort(15) == 15);
    QVERIFY(value09->toShort(16) ==  4);
    QVERIFY(value10->toShort(23) == 15);
    QVERIFY(value11->toShort(42) == 16);
    QVERIFY(value12->toShort(4) == 23);
    QVERIFY(value13->toShort(8) == 42);
    QVERIFY(value14->toShort(15) ==  4);
    QVERIFY(value15->toShort(16) ==  8);
    QVERIFY(value16->toShort(23) == 15);
    QVERIFY(value17->toShort(42) == 16);
    QVERIFY(value18->toShort(4) == 23);
    QVERIFY(value19->toShort(8) == 42);

    QVERIFY(value00->to<short>(4) ==  4);
    QVERIFY(value01->to<short>(8) ==  8);
    QVERIFY(value02->to<short>(15) == 15);
    QVERIFY(value03->to<short>(16) == 16);
    QVERIFY(value04->to<short>(23) == 23);
    QVERIFY(value05->to<short>(42) == 42);
    QVERIFY(value06->to<short>(4) ==  4);
    QVERIFY(value07->to<short>(8) ==  8);
    QVERIFY(value08->to<short>(15) == 15);
    QVERIFY(value09->to<short>(16) == 16);
    QVERIFY(value10->to<short>(23) == 23);
    QVERIFY(value11->to<short>(42) == 42);
    QVERIFY(value12->to<short>(4) ==  4);
    QVERIFY(value13->to<short>(8) ==  8);
    QVERIFY(value14->to<short>(15) == 15);
    QVERIFY(value15->to<short>(16) == 16);
    QVERIFY(value16->to<short>(23) == 23);
    QVERIFY(value17->to<short>(42) == 42);
    QVERIFY(value18->to<short>(4) ==  4);
    QVERIFY(value19->to<short>(8) ==  8);

    QVERIFY(value00->toUShort() == 0);
    QVERIFY(value01->toUShort() == 1);
    QVERIFY(value02->toUShort() == 0);
    QVERIFY(value03->toUShort() == 4);
    QVERIFY(value04->toUShort() == 4);
    QVERIFY(value05->toUShort() == 0);
    QVERIFY(value06->toUShort() == 0);
    QVERIFY(value07->toUShort() == 0);
    QVERIFY(value08->toUShort() == 0);
    QVERIFY(value09->toUShort() == 4);
    QVERIFY(value10->toUShort() == 15);
    QVERIFY(value11->toUShort() == 16);
    QVERIFY(value12->toUShort() == 23);
    QVERIFY(value13->toUShort() == 42);
    QVERIFY(value14->toUShort() == 4);
    QVERIFY(value15->toUShort() == 8);
    QVERIFY(value16->toUShort() == 15);
    QVERIFY(value17->toUShort() == 16);
    QVERIFY(value18->toUShort() == 23);
    QVERIFY(value19->toUShort() == 42);

    QVERIFY(value00->toUShort(4) ==  4);
    QVERIFY(value01->toUShort(8) ==  8);
    QVERIFY(value02->toUShort(15) == 15);
    QVERIFY(value03->toUShort(16) ==  4);
    QVERIFY(value04->toUShort(23) == 23);
    QVERIFY(value05->toUShort(42) == 42);
    QVERIFY(value06->toUShort(4) ==  4);
    QVERIFY(value07->toUShort(8) ==  8);
    QVERIFY(value08->toUShort(15) == 15);
    QVERIFY(value09->toUShort(16) ==  4);
    QVERIFY(value10->toUShort(23) == 15);
    QVERIFY(value11->toUShort(42) == 16);
    QVERIFY(value12->toUShort(4) == 23);
    QVERIFY(value13->toUShort(8) == 42);
    QVERIFY(value14->toUShort(15) ==  4);
    QVERIFY(value15->toUShort(16) ==  8);
    QVERIFY(value16->toUShort(23) == 15);
    QVERIFY(value17->toUShort(42) == 16);
    QVERIFY(value18->toUShort(4) == 23);
    QVERIFY(value19->toUShort(8) == 42);

    QVERIFY(value00->to<unsigned short>(4) ==  4);
    QVERIFY(value01->to<unsigned short>(8) ==  8);
    QVERIFY(value02->to<unsigned short>(15) == 15);
    QVERIFY(value03->to<unsigned short>(16) == 16);
    QVERIFY(value04->to<unsigned short>(23) == 23);
    QVERIFY(value05->to<unsigned short>(42) == 42);
    QVERIFY(value06->to<unsigned short>(4) ==  4);
    QVERIFY(value07->to<unsigned short>(8) ==  8);
    QVERIFY(value08->to<unsigned short>(15) == 15);
    QVERIFY(value09->to<unsigned short>(16) == 16);
    QVERIFY(value10->to<unsigned short>(23) == 23);
    QVERIFY(value11->to<unsigned short>(42) == 42);
    QVERIFY(value12->to<unsigned short>(4) ==  4);
    QVERIFY(value13->to<unsigned short>(8) ==  8);
    QVERIFY(value14->to<unsigned short>(15) == 15);
    QVERIFY(value15->to<unsigned short>(16) == 16);
    QVERIFY(value16->to<unsigned short>(23) == 23);
    QVERIFY(value17->to<unsigned short>(42) == 42);
    QVERIFY(value18->to<unsigned short>(4) ==  4);
    QVERIFY(value19->to<unsigned short>(8) ==  8);

    QVERIFY(value00->toInt() == 0);
    QVERIFY(value01->toInt() == 1);
    QVERIFY(value02->toInt() == 0);
    QVERIFY(value03->toInt() == 4);
    QVERIFY(value04->toInt() == 4);
    QVERIFY(value05->toInt() == 0);
    QVERIFY(value06->toInt() == 0);
    QVERIFY(value07->toInt() == 0);
    QVERIFY(value08->toInt() == 0);
    QVERIFY(value09->toInt() == 4);
    QVERIFY(value10->toInt() == 15);
    QVERIFY(value11->toInt() == 16);
    QVERIFY(value12->toInt() == 23);
    QVERIFY(value13->toInt() == 42);
    QVERIFY(value14->toInt() == 4);
    QVERIFY(value15->toInt() == 8);
    QVERIFY(value16->toInt() == 15);
    QVERIFY(value17->toInt() == 16);
    QVERIFY(value18->toInt() == 23);
    QVERIFY(value19->toInt() == 42);

    QVERIFY(value00->toInt(4) ==  4);
    QVERIFY(value01->toInt(8) ==  8);
    QVERIFY(value02->toInt(15) == 15);
    QVERIFY(value03->toInt(16) ==  4);
    QVERIFY(value04->toInt(23) == 23);
    QVERIFY(value05->toInt(42) == 42);
    QVERIFY(value06->toInt(4) ==  4);
    QVERIFY(value07->toInt(8) ==  8);
    QVERIFY(value08->toInt(15) == 15);
    QVERIFY(value09->toInt(16) ==  4);
    QVERIFY(value10->toInt(23) == 15);
    QVERIFY(value11->toInt(42) == 16);
    QVERIFY(value12->toInt(4) == 23);
    QVERIFY(value13->toInt(8) == 42);
    QVERIFY(value14->toInt(15) ==  4);
    QVERIFY(value15->toInt(16) ==  8);
    QVERIFY(value16->toInt(23) == 15);
    QVERIFY(value17->toInt(42) == 16);
    QVERIFY(value18->toInt(4) == 23);
    QVERIFY(value19->toInt(8) == 42);

    QVERIFY(value00->to<int>(4) ==  4);
    QVERIFY(value01->to<int>(8) ==  8);
    QVERIFY(value02->to<int>(15) == 15);
    QVERIFY(value03->to<int>(16) == 16);
    QVERIFY(value04->to<int>(23) == 23);
    QVERIFY(value05->to<int>(42) == 42);
    QVERIFY(value06->to<int>(4) ==  4);
    QVERIFY(value07->to<int>(8) ==  8);
    QVERIFY(value08->to<int>(15) == 15);
    QVERIFY(value09->to<int>(16) == 16);
    QVERIFY(value10->to<int>(23) == 23);
    QVERIFY(value11->to<int>(42) == 42);
    QVERIFY(value12->to<int>(4) ==  4);
    QVERIFY(value13->to<int>(8) ==  8);
    QVERIFY(value14->to<int>(15) == 15);
    QVERIFY(value15->to<int>(16) == 16);
    QVERIFY(value16->to<int>(23) == 23);
    QVERIFY(value17->to<int>(42) == 42);
    QVERIFY(value18->to<int>(4) ==  4);
    QVERIFY(value19->to<int>(8) ==  8);

    QVERIFY(value00->toUInt() == 0);
    QVERIFY(value01->toUInt() == 1);
    QVERIFY(value02->toUInt() == 0);
    QVERIFY(value03->toUInt() == 4);
    QVERIFY(value04->toUInt() == 4);
    QVERIFY(value05->toUInt() == 0);
    QVERIFY(value06->toUInt() == 0);
    QVERIFY(value07->toUInt() == 0);
    QVERIFY(value08->toUInt() == 0);
    QVERIFY(value09->toUInt() == 4);
    QVERIFY(value10->toUInt() == 15);
    QVERIFY(value11->toUInt() == 16);
    QVERIFY(value12->toUInt() == 23);
    QVERIFY(value13->toUInt() == 42);
    QVERIFY(value14->toUInt() == 4);
    QVERIFY(value15->toUInt() == 8);
    QVERIFY(value16->toUInt() == 15);
    QVERIFY(value17->toUInt() == 16);
    QVERIFY(value18->toUInt() == 23);
    QVERIFY(value19->toUInt() == 42);

    QVERIFY(value00->toUInt(4) ==  4);
    QVERIFY(value01->toUInt(8) ==  8);
    QVERIFY(value02->toUInt(15) == 15);
    QVERIFY(value03->toUInt(16) ==  4);
    QVERIFY(value04->toUInt(23) == 23);
    QVERIFY(value05->toUInt(42) == 42);
    QVERIFY(value06->toUInt(4) ==  4);
    QVERIFY(value07->toUInt(8) ==  8);
    QVERIFY(value08->toUInt(15) == 15);
    QVERIFY(value09->toUInt(16) ==  4);
    QVERIFY(value10->toUInt(23) == 15);
    QVERIFY(value11->toUInt(42) == 16);
    QVERIFY(value12->toUInt(4) == 23);
    QVERIFY(value13->toUInt(8) == 42);
    QVERIFY(value14->toUInt(15) ==  4);
    QVERIFY(value15->toUInt(16) ==  8);
    QVERIFY(value16->toUInt(23) == 15);
    QVERIFY(value17->toUInt(42) == 16);
    QVERIFY(value18->toUInt(4) == 23);
    QVERIFY(value19->toUInt(8) == 42);

    QVERIFY(value00->to<unsigned int>(4) ==  4);
    QVERIFY(value01->to<unsigned int>(8) ==  8);
    QVERIFY(value02->to<unsigned int>(15) == 15);
    QVERIFY(value03->to<unsigned int>(16) == 16);
    QVERIFY(value04->to<unsigned int>(23) == 23);
    QVERIFY(value05->to<unsigned int>(42) == 42);
    QVERIFY(value06->to<unsigned int>(4) ==  4);
    QVERIFY(value07->to<unsigned int>(8) ==  8);
    QVERIFY(value08->to<unsigned int>(15) == 15);
    QVERIFY(value09->to<unsigned int>(16) == 16);
    QVERIFY(value10->to<unsigned int>(23) == 23);
    QVERIFY(value11->to<unsigned int>(42) == 42);
    QVERIFY(value12->to<unsigned int>(4) ==  4);
    QVERIFY(value13->to<unsigned int>(8) ==  8);
    QVERIFY(value14->to<unsigned int>(15) == 15);
    QVERIFY(value15->to<unsigned int>(16) == 16);
    QVERIFY(value16->to<unsigned int>(23) == 23);
    QVERIFY(value17->to<unsigned int>(42) == 42);
    QVERIFY(value18->to<unsigned int>(4) ==  4);
    QVERIFY(value19->to<unsigned int>(8) ==  8);

    QVERIFY(value00->toLong() == 0);
    QVERIFY(value01->toLong() == 1);
    QVERIFY(value02->toLong() == 0);
    QVERIFY(value03->toLong() == 4);
    QVERIFY(value04->toLong() == 4);
    QVERIFY(value05->toLong() == 0);
    QVERIFY(value06->toLong() == 0);
    QVERIFY(value07->toLong() == 0);
    QVERIFY(value08->toLong() == 0);
    QVERIFY(value09->toLong() == 4);
    QVERIFY(value10->toLong() == 15);
    QVERIFY(value11->toLong() == 16);
    QVERIFY(value12->toLong() == 23);
    QVERIFY(value13->toLong() == 42);
    QVERIFY(value14->toLong() == 4);
    QVERIFY(value15->toLong() == 8);
    QVERIFY(value16->toLong() == 15);
    QVERIFY(value17->toLong() == 16);
    QVERIFY(value18->toLong() == 23);
    QVERIFY(value19->toLong() == 42);

    QVERIFY(value00->toLong(4) ==  4);
    QVERIFY(value01->toLong(8) ==  8);
    QVERIFY(value02->toLong(15) == 15);
    QVERIFY(value03->toLong(16) ==  4);
    QVERIFY(value04->toLong(23) == 23);
    QVERIFY(value05->toLong(42) == 42);
    QVERIFY(value06->toLong(4) ==  4);
    QVERIFY(value07->toLong(8) ==  8);
    QVERIFY(value08->toLong(15) == 15);
    QVERIFY(value09->toLong(16) ==  4);
    QVERIFY(value10->toLong(23) == 15);
    QVERIFY(value11->toLong(42) == 16);
    QVERIFY(value12->toLong(4) == 23);
    QVERIFY(value13->toLong(8) == 42);
    QVERIFY(value14->toLong(15) ==  4);
    QVERIFY(value15->toLong(16) ==  8);
    QVERIFY(value16->toLong(23) == 15);
    QVERIFY(value17->toLong(42) == 16);
    QVERIFY(value18->toLong(4) == 23);
    QVERIFY(value19->toLong(8) == 42);

    QVERIFY(value00->to<long>(4) ==  4);
    QVERIFY(value01->to<long>(8) ==  8);
    QVERIFY(value02->to<long>(15) == 15);
    QVERIFY(value03->to<long>(16) == 16);
    QVERIFY(value04->to<long>(23) == 23);
    QVERIFY(value05->to<long>(42) == 42);
    QVERIFY(value06->to<long>(4) ==  4);
    QVERIFY(value07->to<long>(8) ==  8);
    QVERIFY(value08->to<long>(15) == 15);
    QVERIFY(value09->to<long>(16) == 16);
    QVERIFY(value10->to<long>(23) == 23);
    QVERIFY(value11->to<long>(42) == 42);
    QVERIFY(value12->to<long>(4) ==  4);
    QVERIFY(value13->to<long>(8) ==  8);
    QVERIFY(value14->to<long>(15) == 15);
    QVERIFY(value15->to<long>(16) == 16);
    QVERIFY(value16->to<long>(23) == 23);
    QVERIFY(value17->to<long>(42) == 42);
    QVERIFY(value18->to<long>(4) ==  4);
    QVERIFY(value19->to<long>(8) ==  8);

    QVERIFY(value00->toULong() == 0);
    QVERIFY(value01->toULong() == 1);
    QVERIFY(value02->toULong() == 0);
    QVERIFY(value03->toULong() == 4);
    QVERIFY(value04->toULong() == 4);
    QVERIFY(value05->toULong() == 0);
    QVERIFY(value06->toULong() == 0);
    QVERIFY(value07->toULong() == 0);
    QVERIFY(value08->toULong() == 0);
    QVERIFY(value09->toULong() == 4);
    QVERIFY(value10->toULong() == 15);
    QVERIFY(value11->toULong() == 16);
    QVERIFY(value12->toULong() == 23);
    QVERIFY(value13->toULong() == 42);
    QVERIFY(value14->toULong() == 4);
    QVERIFY(value15->toULong() == 8);
    QVERIFY(value16->toULong() == 15);
    QVERIFY(value17->toULong() == 16);
    QVERIFY(value18->toULong() == 23);
    QVERIFY(value19->toULong() == 42);

    QVERIFY(value00->toULong(4) ==  4);
    QVERIFY(value01->toULong(8) ==  8);
    QVERIFY(value02->toULong(15) == 15);
    QVERIFY(value03->toULong(16) ==  4);
    QVERIFY(value04->toULong(23) == 23);
    QVERIFY(value05->toULong(42) == 42);
    QVERIFY(value06->toULong(4) ==  4);
    QVERIFY(value07->toULong(8) ==  8);
    QVERIFY(value08->toULong(15) == 15);
    QVERIFY(value09->toULong(16) ==  4);
    QVERIFY(value10->toULong(23) == 15);
    QVERIFY(value11->toULong(42) == 16);
    QVERIFY(value12->toULong(4) == 23);
    QVERIFY(value13->toULong(8) == 42);
    QVERIFY(value14->toULong(15) ==  4);
    QVERIFY(value15->toULong(16) ==  8);
    QVERIFY(value16->toULong(23) == 15);
    QVERIFY(value17->toULong(42) == 16);
    QVERIFY(value18->toULong(4) == 23);
    QVERIFY(value19->toULong(8) == 42);

    QVERIFY(value00->to<unsigned long>(4) ==  4);
    QVERIFY(value01->to<unsigned long>(8) ==  8);
    QVERIFY(value02->to<unsigned long>(15) == 15);
    QVERIFY(value03->to<unsigned long>(16) == 16);
    QVERIFY(value04->to<unsigned long>(23) == 23);
    QVERIFY(value05->to<unsigned long>(42) == 42);
    QVERIFY(value06->to<unsigned long>(4) ==  4);
    QVERIFY(value07->to<unsigned long>(8) ==  8);
    QVERIFY(value08->to<unsigned long>(15) == 15);
    QVERIFY(value09->to<unsigned long>(16) == 16);
    QVERIFY(value10->to<unsigned long>(23) == 23);
    QVERIFY(value11->to<unsigned long>(42) == 42);
    QVERIFY(value12->to<unsigned long>(4) ==  4);
    QVERIFY(value13->to<unsigned long>(8) ==  8);
    QVERIFY(value14->to<unsigned long>(15) == 15);
    QVERIFY(value15->to<unsigned long>(16) == 16);
    QVERIFY(value16->to<unsigned long>(23) == 23);
    QVERIFY(value17->to<unsigned long>(42) == 42);
    QVERIFY(value18->to<unsigned long>(4) ==  4);
    QVERIFY(value19->to<unsigned long>(8) ==  8);

    QVERIFY(value00->toLongLong() == 0);
    QVERIFY(value01->toLongLong() == 1);
    QVERIFY(value02->toLongLong() == 0);
    QVERIFY(value03->toLongLong() == 4);
    QVERIFY(value04->toLongLong() == 4);
    QVERIFY(value05->toLongLong() == 0);
    QVERIFY(value06->toLongLong() == 0);
    QVERIFY(value07->toLongLong() == 0);
    QVERIFY(value08->toLongLong() == 0);
    QVERIFY(value09->toLongLong() == 4);
    QVERIFY(value10->toLongLong() == 15);
    QVERIFY(value11->toLongLong() == 16);
    QVERIFY(value12->toLongLong() == 23);
    QVERIFY(value13->toLongLong() == 42);
    QVERIFY(value14->toLongLong() == 4);
    QVERIFY(value15->toLongLong() == 8);
    QVERIFY(value16->toLongLong() == 15);
    QVERIFY(value17->toLongLong() == 16);
    QVERIFY(value18->toLongLong() == 23);
    QVERIFY(value19->toLongLong() == 42);

    QVERIFY(value00->toLongLong(4) ==  4);
    QVERIFY(value01->toLongLong(8) ==  8);
    QVERIFY(value02->toLongLong(15) == 15);
    QVERIFY(value03->toLongLong(16) ==  4);
    QVERIFY(value04->toLongLong(23) == 23);
    QVERIFY(value05->toLongLong(42) == 42);
    QVERIFY(value06->toLongLong(4) ==  4);
    QVERIFY(value07->toLongLong(8) ==  8);
    QVERIFY(value08->toLongLong(15) == 15);
    QVERIFY(value09->toLongLong(16) ==  4);
    QVERIFY(value10->toLongLong(23) == 15);
    QVERIFY(value11->toLongLong(42) == 16);
    QVERIFY(value12->toLongLong(4) == 23);
    QVERIFY(value13->toLongLong(8) == 42);
    QVERIFY(value14->toLongLong(15) ==  4);
    QVERIFY(value15->toLongLong(16) ==  8);
    QVERIFY(value16->toLongLong(23) == 15);
    QVERIFY(value17->toLongLong(42) == 16);
    QVERIFY(value18->toLongLong(4) == 23);
    QVERIFY(value19->toLongLong(8) == 42);

    QVERIFY(value00->to<long long>(4) ==  4);
    QVERIFY(value01->to<long long>(8) ==  8);
    QVERIFY(value02->to<long long>(15) == 15);
    QVERIFY(value03->to<long long>(16) == 16);
    QVERIFY(value04->to<long long>(23) == 23);
    QVERIFY(value05->to<long long>(42) == 42);
    QVERIFY(value06->to<long long>(4) ==  4);
    QVERIFY(value07->to<long long>(8) ==  8);
    QVERIFY(value08->to<long long>(15) == 15);
    QVERIFY(value09->to<long long>(16) == 16);
    QVERIFY(value10->to<long long>(23) == 23);
    QVERIFY(value11->to<long long>(42) == 42);
    QVERIFY(value12->to<long long>(4) ==  4);
    QVERIFY(value13->to<long long>(8) ==  8);
    QVERIFY(value14->to<long long>(15) == 15);
    QVERIFY(value15->to<long long>(16) == 16);
    QVERIFY(value16->to<long long>(23) == 23);
    QVERIFY(value17->to<long long>(42) == 42);
    QVERIFY(value18->to<long long>(4) ==  4);
    QVERIFY(value19->to<long long>(8) ==  8);

    QVERIFY(value00->toULongLong() == 0);
    QVERIFY(value01->toULongLong() == 1);
    QVERIFY(value02->toULongLong() == 0);
    QVERIFY(value03->toULongLong() == 4);
    QVERIFY(value04->toULongLong() == 4);
    QVERIFY(value05->toULongLong() == 0);
    QVERIFY(value06->toULongLong() == 0);
    QVERIFY(value07->toULongLong() == 0);
    QVERIFY(value08->toULongLong() == 0);
    QVERIFY(value09->toULongLong() == 4);
    QVERIFY(value10->toULongLong() == 15);
    QVERIFY(value11->toULongLong() == 16);
    QVERIFY(value12->toULongLong() == 23);
    QVERIFY(value13->toULongLong() == 42);
    QVERIFY(value14->toULongLong() == 4);
    QVERIFY(value15->toULongLong() == 8);
    QVERIFY(value16->toULongLong() == 15);
    QVERIFY(value17->toULongLong() == 16);
    QVERIFY(value18->toULongLong() == 23);
    QVERIFY(value19->toULongLong() == 42);

    QVERIFY(value00->toULongLong(4) ==  4);
    QVERIFY(value01->toULongLong(8) ==  8);
    QVERIFY(value02->toULongLong(15) == 15);
    QVERIFY(value03->toULongLong(16) ==  4);
    QVERIFY(value04->toULongLong(23) == 23);
    QVERIFY(value05->toULongLong(42) == 42);
    QVERIFY(value06->toULongLong(4) ==  4);
    QVERIFY(value07->toULongLong(8) ==  8);
    QVERIFY(value08->toULongLong(15) == 15);
    QVERIFY(value09->toULongLong(16) ==  4);
    QVERIFY(value10->toULongLong(23) == 15);
    QVERIFY(value11->toULongLong(42) == 16);
    QVERIFY(value12->toULongLong(4) == 23);
    QVERIFY(value13->toULongLong(8) == 42);
    QVERIFY(value14->toULongLong(15) ==  4);
    QVERIFY(value15->toULongLong(16) ==  8);
    QVERIFY(value16->toULongLong(23) == 15);
    QVERIFY(value17->toULongLong(42) == 16);
    QVERIFY(value18->toULongLong(4) == 23);
    QVERIFY(value19->toULongLong(8) == 42);

    QVERIFY(value00->to<unsigned long long>(4) ==  4);
    QVERIFY(value01->to<unsigned long long>(8) ==  8);
    QVERIFY(value02->to<unsigned long long>(15) == 15);
    QVERIFY(value03->to<unsigned long long>(16) == 16);
    QVERIFY(value04->to<unsigned long long>(23) == 23);
    QVERIFY(value05->to<unsigned long long>(42) == 42);
    QVERIFY(value06->to<unsigned long long>(4) ==  4);
    QVERIFY(value07->to<unsigned long long>(8) ==  8);
    QVERIFY(value08->to<unsigned long long>(15) == 15);
    QVERIFY(value09->to<unsigned long long>(16) == 16);
    QVERIFY(value10->to<unsigned long long>(23) == 23);
    QVERIFY(value11->to<unsigned long long>(42) == 42);
    QVERIFY(value12->to<unsigned long long>(4) ==  4);
    QVERIFY(value13->to<unsigned long long>(8) ==  8);
    QVERIFY(value14->to<unsigned long long>(15) == 15);
    QVERIFY(value15->to<unsigned long long>(16) == 16);
    QVERIFY(value16->to<unsigned long long>(23) == 23);
    QVERIFY(value17->to<unsigned long long>(42) == 42);
    QVERIFY(value18->to<unsigned long long>(4) ==  4);
    QVERIFY(value19->to<unsigned long long>(8) ==  8);
}

void TestJson::QMJsonValue_string(void)
{
    auto value00 = QMPointer<QMJsonValue>(new QMJsonValue());
    auto value01 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value02 = QMPointer<QMJsonValue>(new QMJsonValue(false));
    auto value03 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto value04 = QMPointer<QMJsonValue>(new QMJsonValue(0));
    auto value05 = QMPointer<QMJsonValue>(new QMJsonValue("true"));
    auto value06 = QMPointer<QMJsonValue>(new QMJsonValue("false"));
    auto value07 = QMPointer<QMJsonValue>(new QMJsonValue("Hello World"));
    auto value08 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonArray));
    auto value09 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonObject));
    auto value10 = QMPointer<QMJsonValue>(new QMJsonValue(QRect()));

    QVERIFY(value00->isString() == false);
    QVERIFY(value01->isString() == false);
    QVERIFY(value02->isString() == false);
    QVERIFY(value03->isString() == false);
    QVERIFY(value04->isString() == false);
    QVERIFY(value05->isString() == true);
    QVERIFY(value06->isString() == true);
    QVERIFY(value07->isString() == true);
    QVERIFY(value08->isString() == false);
    QVERIFY(value09->isString() == false);
    QVERIFY(value10->isString() == false);

    QVERIFY(value00->toString() == "null");
    QVERIFY(value01->toString() == "true");
    QVERIFY(value02->toString() == "false");
    QVERIFY(value03->toString() == "4.8");
    QVERIFY(value04->toString() == "0");
    QVERIFY(value05->toString() == "true");
    QVERIFY(value06->toString() == "false");
    QVERIFY(value07->toString() == "Hello World");
    QVERIFY(value08->toString() == "");
    QVERIFY(value09->toString() == "");
    QVERIFY(value10->toString() == "");

    QVERIFY(value00->toString("15.16") == "15.16");
    QVERIFY(value01->toString("15.16") == "15.16");
    QVERIFY(value02->toString("15.16") == "15.16");
    QVERIFY(value03->toString("15.16") == "15.16");
    QVERIFY(value04->toString("15.16") == "15.16");
    QVERIFY(value05->toString("15.16") == "true");
    QVERIFY(value06->toString("15.16") == "false");
    QVERIFY(value07->toString("15.16") == "Hello World");
    QVERIFY(value08->toString("15.16") == "15.16");
    QVERIFY(value09->toString("15.16") == "15.16");
    QVERIFY(value10->toString("15.16") == "15.16");

    QVERIFY(value00->to<QString>("15.16") == "15.16");
    QVERIFY(value01->to<QString>("15.16") == "15.16");
    QVERIFY(value02->to<QString>("15.16") == "15.16");
    QVERIFY(value03->to<QString>("15.16") == "15.16");
    QVERIFY(value04->to<QString>("15.16") == "15.16");
    QVERIFY(value05->to<QString>("15.16") == "true");
    QVERIFY(value06->to<QString>("15.16") == "false");
    QVERIFY(value07->to<QString>("15.16") == "Hello World");
    QVERIFY(value08->to<QString>("15.16") == "15.16");
    QVERIFY(value09->to<QString>("15.16") == "15.16");
    QVERIFY(value10->to<QString>("15.16") == "15.16");

    QVERIFY(value00->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value01->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value02->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value03->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value04->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value05->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value06->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value07->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value08->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value09->to<const char *>("15.16") == QString("15.16"));
    QVERIFY(value10->to<const char *>("15.16") == QString("15.16"));
}

void TestJson::QMJsonValue_array(void)
{
    auto value00 = QMPointer<QMJsonValue>(new QMJsonValue());
    auto value01 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value02 = QMPointer<QMJsonValue>(new QMJsonValue(false));
    auto value03 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto value04 = QMPointer<QMJsonValue>(new QMJsonValue(0));
    auto value05 = QMPointer<QMJsonValue>(new QMJsonValue("true"));
    auto value06 = QMPointer<QMJsonValue>(new QMJsonValue("false"));
    auto value07 = QMPointer<QMJsonValue>(new QMJsonValue("Hello World"));
    auto value08 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonArray));
    auto value09 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonObject));
    auto value10 = QMPointer<QMJsonValue>(new QMJsonValue(QRect()));
    auto array1 = QMPointer<QMJsonArray>(new QMJsonArray());

    value08->toArray()->append(value00);
    value08->toArray()->append(value00);
    value08->toArray()->append(value00);

    array1->append(value00);
    array1->append(value00);

    QVERIFY(value00->isArray() == false);
    QVERIFY(value01->isArray() == false);
    QVERIFY(value02->isArray() == false);
    QVERIFY(value03->isArray() == false);
    QVERIFY(value04->isArray() == false);
    QVERIFY(value05->isArray() == false);
    QVERIFY(value06->isArray() == false);
    QVERIFY(value07->isArray() == false);
    QVERIFY(value08->isArray() == true);
    QVERIFY(value09->isArray() == false);
    QVERIFY(value10->isArray() == false);

    QVERIFY(value00->toArray()->count() == 0);
    QVERIFY(value01->toArray()->count() == 0);
    QVERIFY(value02->toArray()->count() == 0);
    QVERIFY(value03->toArray()->count() == 0);
    QVERIFY(value04->toArray()->count() == 0);
    QVERIFY(value05->toArray()->count() == 0);
    QVERIFY(value06->toArray()->count() == 0);
    QVERIFY(value07->toArray()->count() == 0);
    QVERIFY(value08->toArray()->count() == 3);
    QVERIFY(value09->toArray()->count() == 0);
    QVERIFY(value10->toArray()->count() == 0);

    QVERIFY(value00->toArray(array1)->count() == 2);
    QVERIFY(value01->toArray(array1)->count() == 2);
    QVERIFY(value02->toArray(array1)->count() == 2);
    QVERIFY(value03->toArray(array1)->count() == 2);
    QVERIFY(value04->toArray(array1)->count() == 2);
    QVERIFY(value05->toArray(array1)->count() == 2);
    QVERIFY(value06->toArray(array1)->count() == 2);
    QVERIFY(value07->toArray(array1)->count() == 2);
    QVERIFY(value08->toArray(array1)->count() == 3);
    QVERIFY(value09->toArray(array1)->count() == 2);
    QVERIFY(value10->toArray(array1)->count() == 2);

    QVERIFY(value00->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value01->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value02->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value03->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value04->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value05->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value06->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value07->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value08->to<QMPointer<QMJsonArray> >(array1)->count() == 3);
    QVERIFY(value09->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
    QVERIFY(value10->to<QMPointer<QMJsonArray> >(array1)->count() == 2);
}

void TestJson::QMJsonValue_object(void)
{
    auto value00 = QMPointer<QMJsonValue>(new QMJsonValue());
    auto value01 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value02 = QMPointer<QMJsonValue>(new QMJsonValue(false));
    auto value03 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto value04 = QMPointer<QMJsonValue>(new QMJsonValue(0));
    auto value05 = QMPointer<QMJsonValue>(new QMJsonValue("true"));
    auto value06 = QMPointer<QMJsonValue>(new QMJsonValue("false"));
    auto value07 = QMPointer<QMJsonValue>(new QMJsonValue("Hello World"));
    auto value08 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonArray));
    auto value09 = QMPointer<QMJsonValue>(new QMJsonValue(new QMJsonObject));
    auto value10 = QMPointer<QMJsonValue>(new QMJsonValue(QRect()));
    auto object1 = QMPointer<QMJsonObject>(new QMJsonObject());

    value09->toObject()->insert("key1", value00);
    value09->toObject()->insert("key2", value00);
    value09->toObject()->insert("key3", value00);

    object1->insert("key1", value00);
    object1->insert("key2", value00);

    QVERIFY(value00->isObject() == false);
    QVERIFY(value01->isObject() == false);
    QVERIFY(value02->isObject() == false);
    QVERIFY(value03->isObject() == false);
    QVERIFY(value04->isObject() == false);
    QVERIFY(value05->isObject() == false);
    QVERIFY(value06->isObject() == false);
    QVERIFY(value07->isObject() == false);
    QVERIFY(value08->isObject() == false);
    QVERIFY(value09->isObject() == true);
    QVERIFY(value10->isObject() == false);

    QVERIFY(value00->toObject()->count() == 0);
    QVERIFY(value01->toObject()->count() == 0);
    QVERIFY(value02->toObject()->count() == 0);
    QVERIFY(value03->toObject()->count() == 0);
    QVERIFY(value04->toObject()->count() == 0);
    QVERIFY(value05->toObject()->count() == 0);
    QVERIFY(value06->toObject()->count() == 0);
    QVERIFY(value07->toObject()->count() == 0);
    QVERIFY(value08->toObject()->count() == 0);
    QVERIFY(value09->toObject()->count() == 3);
    QVERIFY(value10->toObject()->count() == 0);

    QVERIFY(value00->toObject(object1)->count() == 2);
    QVERIFY(value01->toObject(object1)->count() == 2);
    QVERIFY(value02->toObject(object1)->count() == 2);
    QVERIFY(value03->toObject(object1)->count() == 2);
    QVERIFY(value04->toObject(object1)->count() == 2);
    QVERIFY(value05->toObject(object1)->count() == 2);
    QVERIFY(value06->toObject(object1)->count() == 2);
    QVERIFY(value07->toObject(object1)->count() == 2);
    QVERIFY(value08->toObject(object1)->count() == 2);
    QVERIFY(value09->toObject(object1)->count() == 3);
    QVERIFY(value10->toObject(object1)->count() == 2);

    QVERIFY(value00->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value01->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value02->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value03->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value04->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value05->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value06->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value07->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value08->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
    QVERIFY(value09->to<QMPointer<QMJsonObject> >(object1)->count() == 3);
    QVERIFY(value10->to<QMPointer<QMJsonObject> >(object1)->count() == 2);
}

void TestJson::QMJsonValue_value(void)
{
    auto value01 = QMPointer<QMJsonValue>(new QMJsonValue(true));
    auto value02 = QMPointer<QMJsonValue>(new QMJsonValue(4.8));
    auto array1 = QMPointer<QMJsonArray>(new QMJsonArray());
    auto array2 = QMPointer<QMJsonArray>(new QMJsonArray());
    auto object1 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto object2 = QMPointer<QMJsonObject>(new QMJsonObject());
    auto value03 = QMPointer<QMJsonValue>(new QMJsonValue(object1));

    object1->insert("array1", array1);
    object2->insert("array2", array2);
    array1->append(object2);
    array2->append(value01);
    array2->append(value02);
    array2->append(value03);

    QVERIFY(value03->value("array1")->value(0)->value("array2")->value(0)->toBool() == true);
    QVERIFY(value03->value("array1")->value(0)->value("array2")->value(1)->toDouble() == 4.8);
}
