language: cpp

compiler:
- clang
- gcc

env:
- QT_BASE=52
- QT_BASE=53
- QT_BASE=54
- QT_BASE=55

before_install:
- if [ "$QT_BASE" = "52" ]; then sudo add-apt-repository ppa:beineri/opt-qt521 -y; fi
- if [ "$QT_BASE" = "53" ]; then sudo add-apt-repository ppa:beineri/opt-qt532 -y; fi
- if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt541 -y; fi
- if [ "$QT_BASE" = "55" ]; then sudo add-apt-repository ppa:beineri/opt-qt55 -y; fi

install:
- sudo apt-get update
- sudo apt-get install build-essential
- if [ "$QT_BASE" = "52" ]; then sudo apt-get install qt52base; source /opt/qt52/bin/qt52-env.sh; fi
- if [ "$QT_BASE" = "53" ]; then sudo apt-get install qt53base; source /opt/qt53/bin/qt53-env.sh; fi
- if [ "$QT_BASE" = "54" ]; then sudo apt-get install qt54base; source /opt/qt54/bin/qt54-env.sh; fi
- if [ "$QT_BASE" = "55" ]; then sudo apt-get install qt55base; source /opt/qt55/bin/qt55-env.sh; fi

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC QMAKE_LINK=$CXX"
- make -j
- sudo make install
- make distclean
- cd test
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC QMAKE_LINK=$CXX"
- make -j
- ./test -platform offscreen
- make distclean
- cd ..
- cd example
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC QMAKE_LINK=$CXX"
- make -j
- ./example
- make distclean
- cd ..
- if [[ -n $(./tools/astyle/linux/run.sh | grep Formatted) ]]; then echo "You must run astyle before submitting a pull request"; exit -1; fi
