language: cpp

compiler:
- clang
- gcc

env:
- QT_BASE=56
- QT_BASE=57
- QT_BASE=58
- QT_BASE=59

before_install:
- if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt563-trusty -y; fi
- if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y; fi
- if [ "$QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y; fi
- if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y; fi

install:
- sudo apt-get update
- sudo apt-get install build-essential
- if [ "$QT_BASE" = "56" ]; then sudo apt-get install qt56base; source /opt/qt56/bin/qt56-env.sh; fi
- if [ "$QT_BASE" = "57" ]; then sudo apt-get install qt57base; source /opt/qt57/bin/qt57-env.sh; fi
- if [ "$QT_BASE" = "58" ]; then sudo apt-get install qt58base; source /opt/qt58/bin/qt58-env.sh; fi
- if [ "$QT_BASE" = "59" ]; then sudo apt-get install qt59base; source /opt/qt59/bin/qt59-env.sh; fi

script:
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX"
- make -j
- sudo make install
- make distclean
- cd test
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX"
- make -j
- ./test -platform offscreen
- make distclean
- cd ..
- cd example
- qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "QMAKE_LINK=$CXX"
- make -j
- ./example
- make distclean
- cd ..
- if [[ -n $(./tools/astyle/linux/run.sh | grep Formatted) ]]; then echo "You must run astyle before submitting a pull request"; exit -1; fi
